#!/bin/sh
# postinst script for python3-smartmeter-datacollector-configurator
#
# see: dh_installdeb(1)

# exit on any error
set -e

echo -n "Installing dependencies using pip.."
# write a pip requirements.txt for automatic dependency installation
echo "-i https://pypi.org/simple
anyio==3.6.2 ; python_full_version >= '3.6.2'
click==8.1.3 ; python_version >= '3.7'
h11==0.14.0 ; python_version >= '3.7'
idna==3.4 ; python_version >= '3.5'
pydantic==1.10.7
sniffio==1.3.0 ; python_version >= '3.7'
starlette==0.27.0
typing-extensions==4.5.0 ; python_version >= '3.7'
uvicorn==0.22.0" > /tmp/requirements.txt
# install all required dependencies
python3 -m pip install -r /tmp/requirements.txt > /dev/null 2>&1
rm /tmp/requirements.txt
echo "..done"

#DEBHELPER#

exit 0
