#!/bin/sh
# postinst script for python3-smartmeter-datacollector-configurator
#
# see: dh_installdeb(1)

# exit on any error
set -e

echo -n "Installing dependencies using pip.."
# write a pip requirements.txt for automatic dependency installation
echo "-i https://pypi.org/simple
anyio==4.3.0 ; python_version >= '3.8'
click==8.1.7 ; python_version >= '3.7'
exceptiongroup==1.2.0 ; python_version < '3.11'
h11==0.14.0 ; python_version >= '3.7'
idna==3.6 ; python_version >= '3.5'
pydantic==1.10.14
sniffio==1.3.1 ; python_version >= '3.7'
starlette==0.37.2
typing-extensions==4.10.0 ; python_version >= '3.8'
uvicorn==0.29.0" > /tmp/requirements.txt
# install all required dependencies
python3 -m pip install -r /tmp/requirements.txt > /dev/null 2>&1
rm /tmp/requirements.txt
echo "..done"

#DEBHELPER#

exit 0
