name: Frontend code checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  check_python_code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/smartmeter-datacollector-configurator

    name: Running frontend code checks
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - id: cache-npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      - name: Setup project with npm
        run: |
          npm ci --ignore-scripts

      - name: Lint with ESLint 
        run: |
          npm run lint
