name: Frontend code checks

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  check_python_code:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: frontend/smartmeter-datacollector-configurator

    name: Running frontend code checks
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: frontend/smartmeter-datacollector-configurator/package-lock.json

      - name: Setup project with npm
        run: |
          npm ci --ignore-scripts

      - name: Lint with ESLint
        run: |
          npm run lint
